#Server Port 번호
server:
  port: 8081
#S3 설정을 위한 클라우드 설정
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}
#스프링 설정 관련
spring:
  #.env 설정
  config:
    import: optional:file:.env[.properties]
  #jwt 키 설정
  jwt:
    secret: ${JWT_SECRET}
  #DB 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #소셜 로그인을 위한 Google, Naver 키 설정
  security:
    oauth2:
      client:
        registration:
          google:
            clientName: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/user.birthday.read
              - https://www.googleapis.com/auth/user.phonenumbers.read
          naver:
            clientName: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirectUri: http://localhost:8080/login/oauth2/code/naver
            authorizationGrantType: authorization_code
            scope:
              - email
              - profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  #출력 창에 나타낼 출력 코드에 대한 정렬 및 DB 생성 방법 관련
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database: mysql
  # 출력 창에 나타날 출력 코드에 대한 포맷
logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: debug
