spring:
  #.env import
  config:
    import: optional:file:.env[.properties]
  frontend:
    url: ${FRONTEND_REDIRECT_URL}
  jwt:
    secret: ${JWT_SECRET}
  datasource:
    url:  ${SPRING_DATASOURCE_URL}
    username : ${SPRING_DATASOURCE_USERNAME}
    password : ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            clientName: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          naver:
            clientName: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirectUri: http://localhost:8080/login/oauth2/code/naver
            authorizationGrantType: authorization_code
            scope:
              - email
              - profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database: mysql
logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: debug
